# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Scientific Computing
author: Henrik Finsberg and Jørgen Dokken
logo: "_static/logo.png"
copyright: "2022"
-description: Developing tools for high performance computing, and applying novel simulation techniques to complex physical processes affecting human health.

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache

# Information about where the book exists on the web
repository:
  url: https://github.com/scientificcomputing/scientificcomputing.github.io # Online location of your book

html:
  use_issues_button: true
  use_repository_button: true
  extra_navbar: See more at <a href="https://www.simula.no/research/scientific-computing">simula.no</a>

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - linkify


sphinx:
  config:
    html_last_updated_fmt: "%b %d, %Y"
    bibtex_bibfiles: ["references.bib"]
    suppress_warnings: ["bibtex.duplicate_citation"] # If the same paper is cited in multiple files

  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinx.ext.napoleon"
    - "sphinx.ext.viewcode"
    - "sphinxcontrib.bibtex"
